### ISSUE TITLE
GraphOverView background

### ISSUE THREAD

**Issue by dylib** [zyantific/IDASkins#20]
Hello, I tried for quite a while to change the GraphOverView background via the stylesheet.qss and unfortunately came up empty. Would you be able to tell me how to change the background from the white to the dark gray so it matches the rest of the theme? Thanks!

![ida](https://cloud.githubusercontent.com/assets/17288131/21468989/9aa150cc-c9ef-11e6-9ec9-ea6c3ebbf928.png)

**Comment by athre0z** [comment]
Mh, actually this is supposed to change according to whatever you configure for your regular graph in IDA. This view is custom and doesn't accept any theming via Qt stylesheets, so it's probably just an IDA bug and not an IDASkins issue. What version of IDA are you working with, what platform?

![tubzdkyt45wzkxp6](https://cloud.githubusercontent.com/assets/6553158/21469013/0fdfac14-ca34-11e6-82e0-44de3fd37bca.png)

Nope, I don't work with that eyesaw, I chose extreme colors for this screenshot. 😃

**Comment by dylib** [comment]
Interesting... I'm currently using version 6.5; I know where the setting is for the standard sized graph, but the mini one didn't seem to change :( 

I tried various combinations in style sheet with things like:
```
IDADockWidget > QWidget > GraphOverView {
    background-color: #666;
    border-radius: 3px;
}
```
...and no change. It probably is a bug then as you say, so maybe time for me to upgrade perhaps. It looks like yours is working properly, which version do you use? Thanks for the quick response!

**Comment by athre0z** [comment]
Stylesheets can't possibly affect IDA custom views (like the graph and the graph preview) because HR decided not to implement theming support via Qt stylesheets for them.

I'm using IDA 6.95 on a Windows 10 VM — that's the latest version. I'm guessing to update your installation is your only option. As this doesn't seem to be an IDASkins issue, I'll close this. Feel free to respond anyways in case you need some more help.
