### ISSUE TITLE
Use IDA Registry API instead of QSettings to get font settings

### ISSUE THREAD

**Issue by L4ys** [zyantific/IDASkins#32]
> IDA uses the registry to store global configuration options that must persist after IDA has been closed.

> On Windows, IDA uses the Windows registry directly. On Unix systems, the registry is stored in a file (typically ~/.idapro/ida.reg).

so we can't get font settings from QSettings on macOS/Linux
I think we should use [IDA Registry API](https://www.hex-rays.com/products/ida/support/sdkdoc/registry_8hpp.html) instead.

```python
# IDA 6.8 on Win7
Python>"Font" in PySide.QtCore.QSettings("Hex-Rays", "IDA").childGroups()
True

Python>idaapi.reg_read_string("Name", "Font\\Disassembly")
Consolas

# IDA 7.0 on macOS 10.12
Python>"Font" in PyQt5.QtCore.QSettings("Hex-Rays", "IDA").childGroups()
False

Python>reg_read_string("Name", "Font\\Disassembly")
Source Code Pro
```

**Comment by athre0z** [comment]
I reversed into idaq.exe and the Linux binary in order to determine how they obtain these settings back when I wrote that code. Under the hood, they use QSettings themselves. Probably we're constructing QSettings with the wrong ini path on Mac/Linux then. Never realised there was an API for accessing the "registry", very interesting. I'll certainly change that code soon™.

**Comment by L4ys** [comment]
I just reversed some idaq.exe from different version
seems that old versions (6.1) use QSettings and new versions (6.8~7.0) use registry api now
