### ISSUE TITLE
Skin does not seem to work on IDA Pro 6.6

### ISSUE THREAD

**Issue by nanotechz9l** [zyantific/IDASkins#4]
Hi,

It seems the skin does not work on IDA 6.6. I also tried idaConsonance but it seems IDA is not recognizing any .clr file I select.

Thanks!

**Comment by athre0z** [comment]
Well, it's been a while since I was last using 6.6, but it worked pretty well there in the past. Also, this plugin doesn't intercept anything related to the stock IDA coloring capabilities, so this problem probably isn't related to IDASkins. Could you provide more detailed information on how you apply your scheme and attach a screenshot of how your IDA looks like?

**Comment by nanotechz9l** [comment]
Thanks for the update. It seemed to be an issue with running IDA in a vm x86 environment. I updated the machine and it works now. Thanks for the rapid response! Very nice theme, best I've seen so far!

**Comment by athre0z** [comment]
Excellent and thanks!
